
CREATE TABLE IF NOT EXISTS role (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE,
    number VARCHAR(20) NOT NULL,
    dob DATE NOT NULL,
    password VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role INT NOT NULL DEFAULT 2, -- default user
    FOREIGN KEY(role) REFERENCES role(id)
);
